### ISSUE TITLE
New notes opens the browser to paper website

### ISSUE THREAD

**Issue by PaulGoutry** [morkro/papyrus#16]
Hi guys, 

First, thanks for your work, really appreciate it !

Just a quick message to notify you that when I create a new note, a new tab in chrome opens with an error message (Screenshot).

<img width="1919" alt="capture d ecran 2018-07-03 a 17 04 05" src="https://user-images.githubusercontent.com/35460895/42228056-47b71234-7ee3-11e8-9d19-88fc53322944.png"><img width="1919" alt="capture d ecran 2018-07-03 a 17 04 05" src="https://user-images.githubusercontent.com/35460895/42228056-47b71234-7ee3-11e8-9d19-88fc53322944.png">

Bye !

 *** 
 ### System information 
 <table><tr><td>Papyrus</td><td>1.0.2</td></tr><tr><td>Electron</td><td>1.4.12</td></tr><tr><td>darwin (x64)</td><td>17.6.0</td></tr></table>

**Comment by morkro** [comment]
Hey, thanks for pointing that out. I will look into that, but am happy for any help on this :)

**Comment by wfranceys** [comment]
Finding the same issue that opening a new note opens a tab in the browser as well. Currently running Papyrus 1.0.2.

**Comment by westlake305** [comment]
Same issue. Every single document I open in the app launches a new Chrome browser tab and fails to connect (as mentioned above).

**Comment by morkro** [comment]
Hmm, that's not good. I didn't have much time to look into this yet, sorry about that. I will spend some time on it this weekend hopefully.

**Comment by timsayshey** [comment]
Yeah, looks like the app is broken. Experiencing the same issue here.

**Comment by jencmart** [comment]
Yeah, same here. Did you find any solution?

**Comment by ughnett** [comment]
Was this issue ever resolved? It's driving me crazy!!

**Comment by sandeeprenjith** [comment]
Experiencing the same issue. App is awesome otherwise

**Comment by Moustachey** [comment]
I'm experiencing the same issue with this app. @morkro will this be getting resolved or is the project abandoned?
I really love the desktop application, this is the only thing that makes it hard to work with though.

**Comment by mattdeekay** [comment]
Just discovered this electron app, I made a PR that fixes the issue, at least for my mac.

**Comment by morkro** [comment]
Hey all, thanks for being patient for so long. I've merged @mattdeekay's work and will prepare a new release the coming days alongside some other improvements.

**Comment by morkro** [comment]
This has been released under [`1.0.3`](https://github.com/morkro/papyrus/releases/tag/1.0.3)
