### ISSUE TITLE
Update Electron Packager

### ISSUE THREAD

**Issue by EriKWDev** [morkro/papyrus#18]
When running
`npm run build:linux`
on Ubuntu 19.10 with Node version 10+, we get a build error stating that we must run Node version 4 or higher. This was fixed in electron-packager 12.0.2^. https://github.com/electron/electron-packager/issues/863

By updating the package.json line 35 to
`"electron-packager": "^12.0.2",`
this fixes the issue.

**Comment by charrismatic** [comment]
I had the same issue on Ubuntu 16.04, the solution you posted fixed the problem for me

**Comment by morkro** [comment]
Thanks for the work!
