### ISSUE TITLE
Support for dark theme?

### ISSUE THREAD

**Issue by Moustachey** [morkro/papyrus#20]
The Dropbox Paper website now supports dark theme, which I believe is based off your OS or Browser theme preference. Can this become an option within Papyrus? It's almost blinding on 4k monitors.

**Comment by dotamir** [comment]
@morkro I can start working on this feature if you need any help here.
Just let me know to start it.

**Comment by morkro** [comment]
@dotamir You can definitely work on this if you'd like ;)

**Comment by morkro** [comment]
Just realise you can actually turn it on/off via the menu now:
<img width="208" alt="Screenshot 2021-06-14 at 17 23 15" src="https://user-images.githubusercontent.com/2461956/121917285-4173c900-cd35-11eb-8149-8edb135fda96.png">
<img width="457" alt="Screenshot 2021-06-14 at 17 23 08" src="https://user-images.githubusercontent.com/2461956/121917293-43d62300-cd35-11eb-988c-c925eafc3c4f.png">


Don't think this is still relevant then.
