### ISSUE TITLE
Can't login on first screen.

### ISSUE THREAD

**Issue by encepps** [morkro/papyrus#8]
Thank you for great app! 
I have a problem with first screen. I can't login.

 ### System information 
 <table><tr><td>Papyrus</td><td>1.0.0</td></tr><tr><td>Electron</td><td>1.4.12</td></tr><tr><td>darwin (x64)</td><td>16.1.0</td></tr></table>

## error message on developer tool
```
Unrecognized Content-Security-Policy directive 'worker-src'.

global_error_handler-vfleAko09.ts:14TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.init (browser.js:88)
browser.js:88 Uncaught TypeError: Cannot read property 'addEventListener' of null
```

Thank you.

**Comment by morkro** [comment]
That is weird. Can you try reloading or restarting the window? I remember having this issue as well once, but never experienced it again.

**Comment by encepps** [comment]
Thank you. I have tried restart mac os and app refresh. But app still not works. Is Papyrus requires some prerequisite?

**Comment by morkro** [comment]
No it doesn't. I have just logged out and encounter the same issue. Not sure if it has anything to do with the updated landing page of Paper. I will work on a fix today :)

**Comment by encepps** [comment]
I appreciate your help! :-)

**Comment by morkro** [comment]
@encepps I have released a new minor version with a potential fix. Can you maybe download the latest [release](https://github.com/morkro/papyrus/releases/tag/1.0.2) and check if it works now?

**Comment by encepps** [comment]
It works! Thank you~ 👍
